admins: []
forwards:
- dest:
  - -1001235484982
  end: null
  offset: '41103'
  source: 1237356033
live:
  delete_on_edit: null
  delete_sync: false
past:
  delay: 2.0
plugins: {}
show_forwarded_from: false
